# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gameinfo_scoreinfo_teamdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='coachEmail',
            field=models.EmailField(default='spam1@laxlink.net', max_length=254),
        ),
    ]
