# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181012_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='conference',
            field=models.CharField(choices=[('NONE', 'No Conference Specified'), ('TGHSLL-N', 'Texas (TGHSLL) North Conference'), ('TGHSLL-C', 'Texas (TGHSLL) Central Conference'), ('TGHSLL-S', 'Texas (TGHSLL) South Conference')], default='NONE', max_length=8),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='state',
            field=models.CharField(choices=[('TX', 'Texas'), ('LA', 'Lousiana'), ('OK', 'Oklahoma')], max_length=2),
        ),
    ]
