# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181012_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreInfo',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='awayTeam',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='gameType',
            new_name='game_type',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='homeTeam',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='coachEmail',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='contactName',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='home_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.TeamData'),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='coach_email',
            field=models.EmailField(default='unknown', max_length=254),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='contact_name',
            field=models.CharField(default='USER', max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='coach',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Team Name'),
        ),
    ]
