# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181012_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='game_validated',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='away_team',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
