# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181012_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='away_team',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='away_team',
            field=models.ManyToManyField(related_name='away', to='app.TeamData'),
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='home_team',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='home_team',
            field=models.ManyToManyField(related_name='home', to='app.TeamData'),
        ),
    ]
