# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181012_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='away_team',
            field=models.ManyToManyField(related_name='away_team', to='app.TeamData'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='home_team',
            field=models.ManyToManyField(related_name='home_team', to='app.TeamData'),
        ),
    ]
