# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181012_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='away_team',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='away_team',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='app.TeamData'),
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='home_team',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='home_team',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='app.TeamData'),
        ),
    ]
