# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181013_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='away_team',
            new_name='Away_team',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='home_team',
            new_name='Home_team',
        ),
    ]
