# Generated by Django 2.1.2 on 2018-10-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181016_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='Away_team',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='app.TeamData'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='Home_team',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='app.TeamData'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='winlosslink_loser',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='loserss_record', to='app.WinLossRecord'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='winlosslink_winner',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='winners_record', to='app.WinLossRecord'),
        ),
        migrations.AlterField(
            model_name='winlossrecord',
            name='teamkey',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='team', to='app.TeamData'),
        ),
    ]
