# Generated by Django 2.1.2 on 2018-10-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181017_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='division',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('HSD1', 'High School D1'), ('HSD2', 'High School D2'), ('HSJV', 'High School JV'), ('NCAAD1', 'NCAA Division 1'), ('NCAAD2', 'NCAA Division 2'), ('NCAAD3', 'NCAA Division 3')], default='Unknown', max_length=6),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='state',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('LA', 'Lousiana'), ('OK', 'Oklahoma'), ('TX', 'Texas')], default='Unknown', max_length=2),
        ),
    ]
