# Generated by Django 2.1.2 on 2018-10-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181018_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='gender',
            field=models.CharField(choices=[('MENS', 'Mens'), ('WOMENS', 'Womens'), ('MIXED', 'Mixed')], default='Mixed', max_length=8),
        ),
    ]
