# Generated by Django 2.1.2 on 2018-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_teamdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='game_type',
            field=models.CharField(choices=[('A', 'Any'), ('S', 'Scrimmage'), ('R', 'Regular Season'), ('P', 'Playoff'), ('C', 'Championship'), ('T', 'Tournament')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='conference',
            field=models.CharField(choices=[('Any', 'Any Conference'), ('TGHSLL-N', 'Texas (TGHSLL) North Conference'), ('TGHSLL-C', 'Texas (TGHSLL) Central Conference'), ('TGHSLL-S', 'Texas (TGHSLL) South Conference')], default='NONE', max_length=8),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='division',
            field=models.CharField(choices=[('ANY', 'Any'), ('HSD1', 'High School D1'), ('HSD2', 'High School D2'), ('HSJV', 'High School JV'), ('NCAAD1', 'NCAA Division 1'), ('NCAAD2', 'NCAA Division 2'), ('NCAAD3', 'NCAA Division 3')], default='Unknown', max_length=6),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='state',
            field=models.CharField(choices=[('ANY', 'Any'), ('LA', 'Lousiana'), ('OK', 'Oklahoma'), ('TX', 'Texas')], default='Unknown', max_length=2),
        ),
        migrations.AlterField(
            model_name='winlossrecord',
            name='season',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter'), ('INDOOR', 'Indoor'), ('TRAVEL', 'Travel'), ('ANY', 'Any')], default='None', max_length=10),
        ),
    ]
