# Generated by Django 2.1.2 on 2018-10-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181024_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='conference',
            field=models.CharField(choices=[('ANY', 'Any Conference'), ('TGHSLL-N', 'Texas (TGHSLL) North Conference'), ('TGHSLL-C', 'Texas (TGHSLL) Central Conference'), ('TGHSLL-S', 'Texas (TGHSLL) South Conference')], default='None', max_length=8),
        ),
    ]
