# Generated by Django 2.1.2 on 2018-10-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favDivision',
            field=models.CharField(choices=[('ANY', 'Any'), ('HSD1', 'High School D1'), ('HSD2', 'High School D2'), ('HSJV', 'High School JV'), ('NCAAD1', 'NCAA Division 1'), ('NCAAD2', 'NCAA Division 2'), ('NCAAD3', 'NCAA Division 3')], default='Any', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favState',
            field=models.CharField(choices=[('ANY', 'Any'), ('LA', 'Lousiana'), ('OK', 'Oklahoma'), ('TX', 'Texas')], default='Any', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favTeams',
            field=models.ManyToManyField(blank=True, null=True, to='app.TeamData', verbose_name='the favorite teams of the user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('CURATOR', 'Curator'), ('REGIONAL_MANAGER', 'Regional Manager'), ('TEAM_MANAGER', 'Team Manager'), ('GENERAL_USER', 'General User')], null=True),
        ),
    ]
