# Generated by Django 2.1.2 on 2018-11-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20181029_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favTeams',
        ),
    ]
